### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by jeanlucaslima** [bradley/Blotter#18]
How can I install with npm to use with webpack? I am not sure I saw it in the documentation.

**Comment by bradley** [comment]
Not currently. I believe you may be able to install it in a local file and reference that path from your `package.json` though. 

You arent the first to ask for this so I'll see about getting that working when I can. The project is also open source if you or anyone else feels like contributing. ;)

**Comment by jeanleonino** [comment]
I would love to PR this! But I think it would be more fair if you publish no npm.com? Or can I do it? Would love to give support and offer this package on npm for blotter.

**Comment by bradley** [comment]
Oh right.... I do have to do that. I'll try to address it this weekend.

**Comment by jeanlucaslima** [comment]
@bradley any help? would you like some help?

**Comment by nestarz** [comment]
Would love too to see it on npm !

**Comment by bradley** [comment]
I gave it an afternoon of work a month or so ago and ran into issues I didnt have time to fix that seemed mostly syntax discrepancies between the third party build libraries... but it's been a while. 

It's on my mind but if Im being honest Ive got a lot of other things going on. If someone would like to volunteer to help out I would 100% support you, otherwise getting blotter updated for NPM isnt on my roadmap right now. Im sorry y'all.

Please contribute if you think it's important and have the time and desire to do so.

**Comment by AndrewSB** [comment]
I appreciate the honesty. You keep doing you bradley ❤ can't wait to see what you come up with next
