### ISSUE TITLE
poor mobile performance

### ISSUE THREAD

**Issue by drac** [bradley/Blotter#20]
Mobile performance is so poor on animating.
Are you planning to improve it or is there a todo list for v2.0.0 so we can help to improve?

btw, good job! :)

**Comment by bradley** [comment]
Yeah Im sorry about that. As for now Im not really sure of any mobile improvements that I will be personally addressing any time soon. Im always happy (seriously) when people report bugs theyve found and especially when a fix is proposed. If anyone finds any specific areas of improvement for mobile please open another ticket or pull request if you've got the fix. 

The documentation site runs pretty choppy in mobile mostly because there is way too much going on. :feelsgood: 

For now it's not great on mobile. 

I hate to close the issue without some kind of fix but given that it's a question Im going to go ahead with that. Love you.
