### ISSUE TITLE
'No loop' parameter

### ISSUE THREAD

**Issue by Serse** [bradley/Blotter#28]
Is there a parameter to avoid the loop in slidingDoorMaterial? For stopping the execution after the first complete animation.
Thanks

**Comment by bradley** [comment]
No there is not. In terms of using `SlidingDoorMaterial`, your only option is to work out the timing in your JavaScript so that you call `pause` on the `renderScope` at the right moment during animation.

The Blotter materials that have so far been packaged with Blotter are what they are, and should server as configurable, but eventually limited, examples of what can be done with Blotter. That is, you have another option here, which is to dig into the source for [SlidingDoorMaterial](https://github.com/bradley/Blotter/blob/master/build/materials/slidingDoorMaterial.js), and to create a new [custom build](https://github.com/bradley/Blotter#making-changes--custom-builds) with modifications made to add any uniform you desire.

I know that's asking a lot, but again, the existing Materials are as they are.

**Comment by Serse** [comment]
Thank you for answering. I appreciate very much your library, I will follow your hint about a custom build.
Keep up the grat job
